HiCommunity/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from common.views import index
from HiCommunity.settings import DEBUG, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^hiadmin/', include('hiadmin.urls.urls', namespace='hiadmin')),
    url(r'^users/', include('users.urls.urls', namespace='users')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

hiadmin/urls/urls.py
# coding=utf-8

from django.conf.urls import url, include

from hiadmin.views import index


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^management/', include('hiadmin.urls.management', namespace='management')),
    url(r'^settings/', include('hiadmin.urls.settings', namespace='settings')),
]

post/urls.py
# coding=utf-8

from django.conf.urls import url

from post import views


urlpatterns = [
    url(r'^index/$', views.post_index_page, name='index'),
]

questions/urls.py
# coding=utf-8

from django.conf.urls import url

from questions import views


urlpatterns = [
    url(r'^$', views.question_index, name='index'),
    # url(r'^(?P<region>\w+)/$', views.question_list_page, name='list_no_board'),
    url(r'^(?P<region>\w+)/(?P<board>\w+)/$', views.question_list_page,
        name='list'),
    url(r'^(?P<region>\w+)/(?P<board>\w+)/(?P<pid>\d+)/$',
        views.question_detail_page, name='detail_page'),
    url(r'^(?P<region>\w+)/(?P<board>\w+)/new_question/$',
        views.new_question, name='new_question'),
    url(r'^(?P<region>\w+)/(?P<board>\w+)/(?P<qid>\d+)/new_answer/$',
        views.new_answer, name='new_answer'),
    url(r'^(?P<region>\w+)/(?P<board>\w+)/(?P<qid>\d+)/new_comment/$',
        views.new_comment, name='new_comment'),
]

questions/models.py
# coding=utf-8
from django.db import models
from users.models import Account


class Region(models.Model):
    """
    Region contains one or more boards
    """
    name = models.CharField(max_length=32, verbose_name='区域名')
    address = models.CharField(max_length=16, verbose_name='区域URL地址')

    def __unicode__(self):
        return '%s Region' % self.name


class Board(models.Model):
    """
    Board
    """
    region = models.ForeignKey(to=Region, related_name='board_of_region')
    name = models.CharField(max_length=32, verbose_name='版块名')
    address = models.CharField(max_length=16, verbose_name='版块URL地址')

    def __str__(self):
        return '%s Board' % self.name


class Question(models.Model):
    """
    Questions belong to a board
    """
    board = models.ForeignKey(to=Board, related_name='question_of_board')
    title = models.CharField(max_length=128, verbose_name='标题')
    content = models.TextField(max_length=65535, verbose_name='内容')
    owner = models.ForeignKey(to=Account, related_name='question_owner')
    answer_count = models.IntegerField(default=0, verbose_name='回答数')
    # metadata = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_at = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    def __str__(self):
        return '%s ...' % self.title if len(self.title) > 20 else self.title

    class Meta:
        ordering = ('-update_at',)


class Answer(models.Model):
    """
    Replies of Questions
    对象为question owner或回帖中的某人
    """
    question = models.ForeignKey(to=Question, related_name='answer_of_question')
    content = models.TextField(max_length=65535, verbose_name='内容')
    up = models.PositiveIntegerField(default=0)
    down = models.PositiveIntegerField(default=0)
    owner = models.ForeignKey(to=Account, related_name='answer_owner')
    comment_count = models.IntegerField(default=0, verbose_name='评论数')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_at = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    def __str__(self):
        content = self.content if len(self.content) > 10 else self.content
        return 'Answer(question id %d): %s ...' % (self.question.id, content)


class Comment(models.Model):
    """
    Comments to an answer
    """
    answer = models.ForeignKey(to=Answer, related_name='comment_of_answer')
    content = models.CharField(max_length=512, verbose_name='评论')
    up = models.PositiveIntegerField(default=0)
    owner = models.ForeignKey(to=Account, related_name='answer_comment_owner')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        content = self.content if len(self.content) > 10 else self.content
        return 'Comment(answer id %d): %s ...' % (self.answer.id, content)

questions/views.py
# coding=utf-8
import json

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import HttpResponse, Http404
from django.template.response import TemplateResponse
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F
from datetime import datetime

from common.constants.common import RET_FORMAT
from common.exception import EmptyContent
from common.utils.string_ import str2int
from questions import models as questions_models
from questions.models import Question, Answer, Comment
from questions.exception import *
from users.models import Account
from users.utils.security import request_method, login_required
from users.utils.session import get_login_session


@request_method('GET')
def question_index(request):
    return TemplateResponse(request, 'questions/index.html')


@request_method('GET')
def question_list_page(request, region, board):
    """
    Question list page
    """

    page = request.GET.get('page')
    items_per_page = str2int(request.GET.get('items', 5), 20)
    question_objects = Question.objects.filter(
        board__address=board,
        board__region__address=region)

    # Pagination
    paginator = Paginator(question_objects, items_per_page)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

    # context
    context = {'questions': questions}
    # Note: regions and board information will be rendered at
    # common/middlewares.py for all templates with a
    # question-started URL.
    # add current region and board to context
    # _ = views_helper.region_and_board_context(region, board)
    # context.update(_)
    return TemplateResponse(request, 'questions/board.html', context=context)


def question_detail_page(request, *args, **kwargs):
    pid = kwargs.get('pid')
    try:
        question_object = Question.objects.get(id=pid)
    except Question.DoesNotExist:
        raise Http404

    context = {'question_detail': question_object,
               'region': kwargs.get('region'),
               'board': kwargs.get('board')}

    return TemplateResponse(request, 'questions/detail.html', context=context)


@login_required()
@request_method('POST')
def new_question(request, region, board, *args, **kwargs):
    ret = RET_FORMAT
    title = request.POST.get('title')
    content = request.POST.get('content')
    if not all((title, content)):
        raise EmptyContent
    uid = get_login_session(request)['id']
    try:
        Question.objects.create(
            title=title,
            content=content,
            owner=Account.objects.get(id=uid),
            board=questions_models.Board.objects.get(address=board))
    except Exception as e:
        print(str(e))
        raise CreateQuestionFailed
    else:
        ret['result'] = True
    return HttpResponse(json.dumps(ret))


@login_required()
@request_method('POST')
def new_answer(request, region, board, qid, **kwargs):
    ret = RET_FORMAT
    content = request.POST.get('content')
    if not content:
        raise EmptyContent
    uid = get_login_session(request)['id']
    try:
        Question.objects.filter(id=qid).update(answer_count=F('answer_count') + 1,
                                               update_at=datetime.utcnow())
        Answer.objects.create(question_id=qid, content=content, owner_id=uid)
    except Exception as e:
        print(str(e))
        raise CreateAnswerFailed
    else:
        ret['result'] = True
    return HttpResponse(json.dumps(ret))


@login_required()
@request_method('POST')
def new_comment(request, region, board, qid, **kwargs):
    ret = RET_FORMAT
    content = request.POST.get('content')
    aid = request.POST.get('aid')
    if not content:
        raise EmptyContent
    uid = get_login_session(request)['id']
    try:
        Comment.objects.create(answer_id=aid,
                               content=content,
                               owner_id=uid)
    except Exception as e:
        print(str(e))
        raise CreateCommentFailed
    else:
        ret['result'] = True
    return HttpResponse(json.dumps(ret))


@login_required()
@request_method('POST')
def close_question(request):
    pass


@login_required('admin')
@request_method('DELETE')
def delete_question(request):
    pass

templates/questions/base.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% block materialize_css %}<link href="{% static 'css/common/ghpages-materialize.css' %}?v=0" rel="stylesheet" type="text/css" media="screen,projection">{% endblock %}
{% block css %}
  <link href="{% static 'css/questions/base.css' %}?v=3" rel="stylesheet">
  {% block question_css %}{% endblock %}
{% endblock %}

{% block question_nav %}
  <nav class="top-nav" style="height: 61px;">
    <div class="container">
      <div class="nav-wrapper"><a class="page-title truncate">{% block question_nav_title %}{% endblock %}</a></div>
    </div>
  </nav>
  <div class="container">
    <a href="#" data-activates="nav-side" class="button-collapse top-nav full hide-on-large-only"><i class="material-icons">menu</i></a>
  </div>
  <ul id="nav-side" class="side-nav fixed">
    <li>
      <div class="user-view">
        <div class="background"><img style="background-color: deepskyblue" src="{% static 'images/common/background/pattern.svg' %}"></div>

          {% if is_login %}
            {% with user=request.session.login_user %}
            <a id="nav-avatar" href="#" title="Hello {{ user.name }}"><img class="circle" src="{{ user.avatar.thumb_small }}" alt="User Avatar"></a>
            <a id="nav-username-btn" href="#"><span class="white-text name">{% ifequal user.role 'admin' %}<span class="yellow-text" title="管理员">[S]</span> {% endifequal %}{{ user.name }}</span></a>
            <a id="nav-email-btn" href="#"><span class="white-text email">{{ user.email }}</span></a>
            <a id="nav-logout-btn" href="{% url 'users:accounts:logout' %}"><span class="white-text email">注销</span></a>
            {% endwith %}
          {% else %}
            <a href="{% url 'users:accounts:login_page' %}{% block nav_login_ref %}{% endblock %}">
              <span class="white-text name">登录</span></a>
            <a href="{% url 'users:accounts:register_page' %}{% block nav_register_ref %}{% endblock %}">
              <span class="white-text name">注册</span></a>
          {% endif %}
      </div>
    </li>

    <!--<li class="search">
      <div class="search-wrapper card">
        <input id="search"><i class="material-icons">search</i>
        <div class="search-results"></div>
      </div>
    </li>-->

    <li class="no-padding">
      <ul class="collapsible collapsible-accordion">
        {% for menu in side_nav_menus %}
          {% with region=menu.region boards=menu.boards %}
            {% if boards|length > 0 %}
            <li class="bold">
              <a class="collapsible-header waves-effect waves-teal">{{ region.name }}</a>
              <div class="collapsible-body">
                <ul>
                  {% for board_item in boards %}
                  <li><a href="{% url 'questions:list' region.address board_item.address %}">
                    {{ board_item.name }}</a></li>
                  {% endfor %}
                </ul>
              </div>
            </li>
            {% endif %}
          {% endwith %}
        {% endfor %}
      </ul>
    </li>

  </ul>
{% endblock %}

{% block content %}
  {% block question_breadcrumb %}
    <nav style="margin-bottom: 20px" class="row">
      <div class="nav-wrapper container">
        <div class="col s12">
          <a href="{% url 'questions:index' %}" class="breadcrumb">首页</a>
          <a class="breadcrumb">{{ current_region.name }}</a>
          <a href="{% url 'questions:list' current_region.address current_board.address %}" class="breadcrumb">{{ current_board.name }}</a>
        </div>
      </div>
    </nav>
  {% endblock %}
  <div class="container">
    {% block question_title %}{% endblock %}
    {% block question_main_content %}{% endblock %}
  </div>

{% endblock %}

{% block js %}
  <script src="{% static 'js/questions/base.js' %}?v=7"></script>
  {% block question_js %}{% endblock %}
{% endblock %}

templates/questions/board.html
{% extends 'questions/base.html' %}
{% load staticfiles %}
{% load humanize %}
{% load my_tags %}
{% block title %}{{ current_region.name }} - {{ current_board.name }}{% endblock %}
{% block question_css %}
  <link href="https://cdn.bootcss.com/quill/1.3.3/quill.core.min.css" rel="stylesheet">
{% endblock %}
{% block question_main_content %}
    <div class="row">
      <div class="col l9 s12">
        {% if questions|length > 0 %}
        <ul class="collection">
          {% for question in questions %}
            <li class="collection-item"><a href="{% url 'questions:detail_page' current_region.address current_board.address question.id %}">{{ question.title }}</a>
              <span class="new badge" data-badge-caption="回答">{{ question.answer_count }}</span>
              <span class="right grey-text">{{ question.create_at|naturaltime }} <a href="#">{{ question.owner.username }}</a></span></li>
          {% endfor %}
        </ul>

        <ul class="pagination">
          {% if questions.has_previous %}
          <li class="waves-effect">
            <a href="?page={{ questions.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
          {% else %}
          <li class="waves-effect disabled">
            <a><i class="material-icons">chevron_left</i></a></li>
          {% endif %}
          {% for page in questions.paginator.page_range %}
            {% ifequal questions.number page %}
              <li class="waves-effect active"><a href="?page={{ page }}">{{ page }}</a></li>
            {% else %}
              <li class="waves-effect"><a href="?page={{ page }}">{{ page }}</a></li>
            {% endifequal %}
          {% endfor %}

          {% if questions.has_next %}
            <li class="waves-effect">
              <a href="?page={{ questions.next_page_number  }}"><i class="material-icons">chevron_right</i></a></li>
          {% else %}
            <li class="waves-effect disabled">
              <a><i class="material-icons">chevron_right</i></a></li>
          {% endif %}
        </ul>
        {% else %}
        <div>还没有任何问题</div>
        {% endif %}
        <div class="divider" style="margin: 30px 0;"></div>
        <div>提问</div>

      </div>

    </div>

    <div class="row">
      <form id="new-question-form" class="col s12" method="post" action="{% url 'questions:new_question' current_region.address current_board.address %}">
        <div class="row">
          <div class="input-field col s9">
            <i class="material-icons prefix">mode_edit</i>
            <input id="new-question-title" type="text" class="validate" minlength="4">
            <label for="new-question-title" data-error="标题至少4位字符">输入标题</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s9">
            <i class="material-icons prefix">mode_edit</i>
            <textarea id="new-question-content" class="materialize-textarea" minlength="10"
                      maxlength="65535"></textarea>
            <label for="new-question-content" data-error="内容至少10个字符">输入内容</label>
          </div>
        </div>
          <button class="btn waves-effect waves-light" type="submit" name="action">提问
{#            <i class="material-icons right">send</i>#}
          </button>
      </form>
    </div>
{% endblock %}

{% block question_js %}
  <script src="{% static 'js/questions/board.js' %}?v=0"></script>
  <script src="https://cdn.bootcss.com/quill/1.3.3/quill.core.min.js"></script>
{% endblock %}

templates/questions/detail.html
{% extends 'questions/base.html' %}
{% load staticfiles %}
{% block question_css %}
  <link href="{% static 'css/questions/detail.css' %}?v=2" rel="stylesheet">
{% endblock %}

{% block question_title %}
  <div class="row">
    <div class="col s12">
      <h1><a class="question-link truncate">{{ question_detail.title }}</a></h1>
    </div>
  </div>

{% endblock %}

{% block question_main_content %}

  {% with answers=question_detail.answer_of_question.all %}
  <div class="row">
    <div class="col l9 m10 s12">
      <input type="hidden" id="csrf-token" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
      <div id="question" class="section scrollspy card-panel grey lighten-5 z-depth-1">
        <div>
          {{ question_detail.content }}
        </div>
        <div class="right-align">
          <span class="grey-text">{{ question_detail.owner.username }} {{ question_detail.create_at }}</span>
        </div>

      </div>

      <div class="divider" style="margin: 30px 0;"></div>
      <div>{% if answers|length > 0 %}{{ answers|length }} 个回答{% else %}暂无回答{% endif %}</div>
      {% for answer in answers %}
        <div id="answer-{{ answer.id }}" class="section scrollspy card-panel grey lighten-5 z-depth-1">
          <div class="right-align grey-text" style="margin-bottom: 20px">{{ forloop.counter }}#</div>
          <div>{{ answer.content|safe }}</div>
          <div class="right-align">
            <span class="grey-text">{{ answer.owner.username }} {{ answer.create_at }}</span>
          </div>
          <div class="divider" style="margin: 30px 0;"></div>
          <div class="row comment-list-wrapper">
            <div class="col s12 comment-list">
            {% with comments=answer.comment_of_answer.all %}
              {% if comments|length > 0 %}
                <ul class="collection">
                  {% for comment in answer.comment_of_answer.all %}
                    <li id="comment-{{ comment.id }}" class="collection-item {% if forloop.counter > 5 %}hide{% endif %}">
                      {{ comment.content }}
                      <div class="right">
                        <a href="#">{{ comment.owner.username }}</a>
                        <span class="grey-text">{{ comment.create_at }}</span>
                      </div>
                    </li>
                  {% endfor %}
                </ul>
                {% if comments|length > 5 %}<div><a style="cursor: pointer" class="grey-text show-more-comments">显示剩余{{ comments|length|add:-5 }}条</a></div>{% endif %}
              {% endif %}
            {% endwith %}
            </div>
          </div>
          <div class="right-align">
            <i class="material-icons grey-text show-comment">expand_more</i>
          </div>
        </div>
      {% endfor %}

      <div class="divider" style="margin: 30px 0;"></div>
      <div>回答</div>
    </div>

    <div class="col hide-on-small-only m2 l3 pin-top">
      <ul class="section table-of-contents pinned">
        {% for answer in answers %}
        <li><a class="truncate" href="#answer-{{ answer.id }}">{{ forloop.counter }}. {{ answer.content|truncatechars:'20' }}</a></li>
        {% endfor %}
      </ul>
    </div>

  </div>
  {% endwith %}

  <div class="row">
      <form id="new-answer-form" class="col l9 m10 s12" method="post" action="{% url 'questions:new_answer' region board question_detail.id %}">
        {% csrf_token %}
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            <textarea id="new-answer-content" class="materialize-textarea" minlength="10"
                      maxlength="65535"></textarea>
            <label for="new-answer-content" data-error="内容至少10个字符">我的答案</label>
          </div>
        </div>
          <button class="btn waves-effect waves-light" type="submit" name="action">回答
            <i class="material-icons right">send</i>
          </button>
      </form>

   </div>
{% endblock %}
{% block question_js %}
  <script src="{% static 'js/questions/detail.js' %}?v=4"></script>
{% endblock %}

templates/questions/index.html
{% extends 'questions/base.html' %}

{% block content %}
{% block question_breadcrumb %}{% endblock %}
<h2>Question Index</h2>
{% endblock %}

templates/questions/region.html
{% extends 'questions/base.html' %}
{% load staticfiles %}
{% block title %}{{ current_region.name }}{% endblock %}
{% block question_main_content %}
  {% for region_item in regions %}
    {% ifequal region_item.address current_region.address %}
      {% for board in region_item.board_of_region.all %}
        <a href="{% url 'questions:list' %}">{{ board }}</a>
      {% endfor %}
    {% endifequal %}
  {% endfor %}
{% endblock %}